/**
 * @practor/generator — TypeScript Client Code Generator
 *
 * Reads a parsed Practor schema (JSON from the Go engine) and generates
 * a type-safe TypeScript client with:
 * - Model types (User, Post, etc.)
 * - Input types (UserCreateInput, UserWhereInput, etc.)
 * - Client class with model delegates
 * - Enum types
 */

import * as fs from "fs";
import * as path from "path";

// ============================================================================
// Schema types (matching Go AST JSON output)
// ============================================================================

interface Schema {
  datasources: Datasource[];
  generators: Generator[];
  models: Model[];
  enums: SchemaEnum[];
}

interface Datasource {
  name: string;
  provider: string;
  url: string;
  isEnvVar: boolean;
  envVarName?: string;
}

interface Generator {
  name: string;
  provider: string;
  output?: string;
}

interface Model {
  name: string;
  fields: Field[];
  dbName?: string;
}

interface Field {
  name: string;
  type: FieldType;
  isList: boolean;
  isOptional: boolean;
  attributes?: FieldAttribute[];
  defaultValue?: DefaultValue;
}

interface FieldType {
  name: string;
  isScalar: boolean;
  isEnum: boolean;
  isModel: boolean;
}

interface FieldAttribute {
  name: string;
  args?: Record<string, unknown>;
}

interface DefaultValue {
  type: number; // 0 = literal, 1 = function, 2 = enum
  value?: unknown;
  funcName?: string;
}

interface SchemaEnum {
  name: string;
  values: { name: string }[];
}

// ============================================================================
// Type mapping
// ============================================================================

const SCALAR_TO_TS: Record<string, string> = {
  String: "string",
  Int: "number",
  Float: "number",
  Boolean: "boolean",
  DateTime: "Date",
  Json: "JsonValue",
  BigInt: "bigint",
  Bytes: "Buffer",
  Decimal: "string", // Prisma-compatible: Decimal as string
};

/** Maps a Practor field type to a TypeScript type string. */
function fieldToTsType(field: Field, enums: Set<string>): string {
  if (field.type.isScalar) {
    return SCALAR_TO_TS[field.type.name] ?? "unknown";
  }
  if (field.type.isEnum || enums.has(field.type.name)) {
    return field.type.name;
  }
  if (field.type.isModel) {
    return field.type.name;
  }
  // Fallback: could be enum or model not yet resolved
  if (enums.has(field.type.name)) {
    return field.type.name;
  }
  return SCALAR_TO_TS[field.type.name] ?? field.type.name;
}

/** Checks if a field has the given attribute. */
function hasAttribute(field: Field, name: string): boolean {
  return field.attributes?.some((a) => a.name === name) ?? false;
}

/** Checks if a field is auto-generated (autoincrement, now, uuid, cuid, updatedAt). */
function isAutoGenerated(field: Field): boolean {
  if (hasAttribute(field, "updatedAt")) return true;
  if (field.defaultValue) {
    if (field.defaultValue.type === 1) {
      const fn = field.defaultValue.funcName;
      return (
        fn === "autoincrement" || fn === "now" || fn === "uuid" || fn === "cuid"
      );
    }
  }
  return false;
}

// ============================================================================
// Code generation
// ============================================================================

/**
 * Generates all TypeScript client code from a schema.
 *
 * @param schema Parsed schema JSON from the Go engine
 * @param outputDir Directory to write generated files
 */
export function generate(schema: Schema, outputDir: string): void {
  fs.mkdirSync(outputDir, { recursive: true });

  const enumNames = new Set(schema.enums.map((e) => e.name));
  const lines: string[] = [];

  // Header
  lines.push("/**");
  lines.push(" * Practor Client — Auto-generated by @practor/generator");
  lines.push(" * DO NOT EDIT MANUALLY");
  lines.push(` * Generated at: ${new Date().toISOString()}`);
  lines.push(" */");
  lines.push("");
  lines.push(
    "import { PractorClient as BasePractorClient, PractorClientOptions, MiddlewareFunction } from '@practor/client';",
  );
  lines.push("");

  // JSON value type
  lines.push(
    "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };",
  );
  lines.push("");

  // Re-export middleware types for convenience
  lines.push(
    "export type { MiddlewareParams, MiddlewareNext, MiddlewareFunction } from '@practor/client';",
  );
  lines.push("");

  // Generate enums
  for (const schemaEnum of schema.enums) {
    lines.push(...generateEnum(schemaEnum));
    lines.push("");
  }

  // Generate model types and input types
  for (const model of schema.models) {
    lines.push(...generateModelType(model, enumNames));
    lines.push("");
    lines.push(...generateWhereInput(model, enumNames));
    lines.push("");
    lines.push(...generateCreateInput(model, enumNames));
    lines.push("");
    lines.push(...generateUpdateInput(model, enumNames));
    lines.push("");
    lines.push(...generateOrderByInput(model));
    lines.push("");
    lines.push(...generateSelectInput(model));
    lines.push("");
    lines.push(...generateIncludeInput(model));
    lines.push("");
  }

  // Generate model delegate interfaces
  for (const model of schema.models) {
    lines.push(...generateDelegateInterface(model));
    lines.push("");
  }

  // Generate the main client class
  lines.push(...generateClientClass(schema));

  // Write the file
  const outputPath = path.join(outputDir, "index.ts");
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}

// ============================================================================
// Enum generation
// ============================================================================

function generateEnum(schemaEnum: SchemaEnum): string[] {
  const lines: string[] = [];
  lines.push(`export const ${schemaEnum.name} = {`);
  for (const value of schemaEnum.values) {
    lines.push(`  ${value.name}: '${value.name}',`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push(
    `export type ${schemaEnum.name} = (typeof ${schemaEnum.name})[keyof typeof ${schemaEnum.name}];`,
  );
  return lines;
}

// ============================================================================
// Model type generation
// ============================================================================

function generateModelType(model: Model, enums: Set<string>): string[] {
  const lines: string[] = [];
  lines.push(`/** ${model.name} model type. */`);
  lines.push(`export interface ${model.name} {`);

  for (const field of model.fields) {
    // Skip relation fields in the base type — they're in the "Include" type
    if (field.type.isModel) continue;

    const tsType = fieldToTsType(field, enums);
    const nullable = field.isOptional ? " | null" : "";
    lines.push(`  ${field.name}: ${tsType}${nullable};`);
  }

  lines.push("}");
  return lines;
}

// ============================================================================
// Where input generation
// ============================================================================

function generateWhereInput(model: Model, enums: Set<string>): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}WhereInput {`);
  lines.push(`  AND?: ${model.name}WhereInput | ${model.name}WhereInput[];`);
  lines.push(`  OR?: ${model.name}WhereInput[];`);
  lines.push(`  NOT?: ${model.name}WhereInput | ${model.name}WhereInput[];`);

  for (const field of model.fields) {
    if (field.type.isModel) continue;

    const tsType = fieldToTsType(field, enums);
    let filterType: string;

    switch (field.type.name) {
      case "String":
        filterType = `string | StringFilter`;
        break;
      case "Int":
      case "Float":
      case "BigInt":
      case "Decimal":
        filterType = `${tsType} | NumberFilter`;
        break;
      case "Boolean":
        filterType = `boolean | BoolFilter`;
        break;
      case "DateTime":
        filterType = `Date | string | DateTimeFilter`;
        break;
      default:
        if (field.type.isEnum || enums.has(field.type.name)) {
          filterType = `${tsType} | EnumFilter<${tsType}>`;
        } else {
          filterType = tsType;
        }
    }

    if (field.isOptional) {
      filterType += " | null";
    }

    lines.push(`  ${field.name}?: ${filterType};`);
  }

  lines.push("}");

  // Where unique input (only ID and unique fields)
  lines.push("");
  lines.push(`export interface ${model.name}WhereUniqueInput {`);
  for (const field of model.fields) {
    if (hasAttribute(field, "id") || hasAttribute(field, "unique")) {
      const tsType = fieldToTsType(field, enums);
      lines.push(`  ${field.name}?: ${tsType};`);
    }
  }
  lines.push("}");

  return lines;
}

// ============================================================================
// Create input generation
// ============================================================================

function generateCreateInput(model: Model, enums: Set<string>): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}CreateInput {`);

  for (const field of model.fields) {
    if (field.type.isModel) continue;

    const tsType = fieldToTsType(field, enums);
    const isOptionalInCreate =
      field.isOptional || isAutoGenerated(field) || field.defaultValue != null;
    const optionalMark = isOptionalInCreate ? "?" : "";
    const nullable = field.isOptional ? " | null" : "";

    lines.push(`  ${field.name}${optionalMark}: ${tsType}${nullable};`);
  }

  lines.push("}");
  return lines;
}

// ============================================================================
// Update input generation
// ============================================================================

function generateUpdateInput(model: Model, enums: Set<string>): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}UpdateInput {`);

  for (const field of model.fields) {
    if (field.type.isModel) continue;
    if (hasAttribute(field, "id")) continue; // Can't update ID

    const tsType = fieldToTsType(field, enums);
    const nullable = field.isOptional ? " | null" : "";

    lines.push(`  ${field.name}?: ${tsType}${nullable};`);
  }

  lines.push("}");
  return lines;
}

// ============================================================================
// OrderBy input generation
// ============================================================================

function generateOrderByInput(model: Model): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}OrderByInput {`);

  for (const field of model.fields) {
    if (field.type.isModel) continue;
    lines.push(`  ${field.name}?: SortOrder;`);
  }

  lines.push("}");
  return lines;
}

// ============================================================================
// Select & Include input generation
// ============================================================================

function generateSelectInput(model: Model): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}Select {`);

  for (const field of model.fields) {
    if (field.type.isModel) {
      if (field.isList) {
        // List relations support nested filtering, ordering, pagination
        lines.push(`  ${field.name}?: boolean | {`);
        lines.push(`    select?: ${field.type.name}Select;`);
        lines.push(`    include?: ${field.type.name}Include;`);
        lines.push(`    where?: ${field.type.name}WhereInput;`);
        lines.push(
          `    orderBy?: ${field.type.name}OrderByInput | ${field.type.name}OrderByInput[];`,
        );
        lines.push(`    take?: number;`);
        lines.push(`    skip?: number;`);
        lines.push(`    cursor?: ${field.type.name}WhereUniqueInput;`);
        lines.push(`    distinct?: string[];`);
        lines.push(`  };`);
      } else {
        // Single relations support select and include
        lines.push(`  ${field.name}?: boolean | {`);
        lines.push(`    select?: ${field.type.name}Select;`);
        lines.push(`    include?: ${field.type.name}Include;`);
        lines.push(`  };`);
      }
    } else {
      lines.push(`  ${field.name}?: boolean;`);
    }
  }

  lines.push("}");
  return lines;
}

function generateIncludeInput(model: Model): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${model.name}Include {`);

  const hasRelations = model.fields.some((f) => f.type.isModel);

  for (const field of model.fields) {
    if (field.type.isModel) {
      if (field.isList) {
        // List relations: boolean or nested query args
        lines.push(`  ${field.name}?: boolean | {`);
        lines.push(`    select?: ${field.type.name}Select;`);
        lines.push(`    include?: ${field.type.name}Include;`);
        lines.push(`    where?: ${field.type.name}WhereInput;`);
        lines.push(
          `    orderBy?: ${field.type.name}OrderByInput | ${field.type.name}OrderByInput[];`,
        );
        lines.push(`    take?: number;`);
        lines.push(`    skip?: number;`);
        lines.push(`    cursor?: ${field.type.name}WhereUniqueInput;`);
        lines.push(`    distinct?: string[];`);
        lines.push(`  };`);
      } else {
        // Single relations: boolean or nested select/include
        lines.push(`  ${field.name}?: boolean | {`);
        lines.push(`    select?: ${field.type.name}Select;`);
        lines.push(`    include?: ${field.type.name}Include;`);
        lines.push(`  };`);
      }
    }
  }

  // If no relations, add index signature to prevent empty interface errors
  if (!hasRelations) {
    lines.push(`  _count?: boolean;`);
  }

  lines.push("}");
  return lines;
}

// ============================================================================
// Delegate interface generation
// ============================================================================

function generateDelegateInterface(model: Model): string[] {
  const name = model.name;

  return [
    `export interface ${name}Delegate {`,
    `  findMany(args?: ${name}FindManyArgs): Promise<${name}[]>;`,
    `  findUnique(args: ${name}FindUniqueArgs): Promise<${name} | null>;`,
    `  findFirst(args?: ${name}FindManyArgs): Promise<${name} | null>;`,
    `  findUniqueOrThrow(args: ${name}FindUniqueArgs): Promise<${name}>;`,
    `  findFirstOrThrow(args?: ${name}FindManyArgs): Promise<${name}>;`,
    `  create(args: { data: ${name}CreateInput; select?: ${name}Select; include?: ${name}Include }): Promise<${name}>;`,
    `  createMany(args: { data: ${name}CreateInput[]; skipDuplicates?: boolean }): Promise<{ count: number }>;`,
    `  update(args: { data: ${name}UpdateInput; where: ${name}WhereUniqueInput; select?: ${name}Select; include?: ${name}Include }): Promise<${name}>;`,
    `  updateMany(args: { data: ${name}UpdateInput; where?: ${name}WhereInput }): Promise<{ count: number }>;`,
    `  delete(args: { where: ${name}WhereUniqueInput; select?: ${name}Select; include?: ${name}Include }): Promise<${name}>;`,
    `  deleteMany(args?: { where?: ${name}WhereInput }): Promise<{ count: number }>;`,
    `  upsert(args: { where: ${name}WhereUniqueInput; create: ${name}CreateInput; update: ${name}UpdateInput }): Promise<${name}>;`,
    `  count(args?: { where?: ${name}WhereInput }): Promise<number>;`,
    `  aggregate(args: ${name}AggregateArgs): Promise<${name}AggregateResult>;`,
    `  groupBy(args: ${name}GroupByArgs): Promise<${name}GroupByResult[]>;`,
    "}",
    "",
    `export interface ${name}FindManyArgs {`,
    `  where?: ${name}WhereInput;`,
    `  select?: ${name}Select;`,
    `  include?: ${name}Include;`,
    `  orderBy?: ${name}OrderByInput | ${name}OrderByInput[];`,
    "  skip?: number;",
    "  take?: number;",
    `  cursor?: ${name}WhereUniqueInput;`,
    "  distinct?: string[];",
    "}",
    "",
    `export interface ${name}FindUniqueArgs {`,
    `  where: ${name}WhereUniqueInput;`,
    `  select?: ${name}Select;`,
    `  include?: ${name}Include;`,
    "}",
    "",
    `export interface ${name}AggregateArgs {`,
    `  where?: ${name}WhereInput;`,
    "  _count?: boolean | Record<string, boolean>;",
    "  _avg?: Record<string, boolean>;",
    "  _sum?: Record<string, boolean>;",
    "  _min?: Record<string, boolean>;",
    "  _max?: Record<string, boolean>;",
    "}",
    "",
    `export type ${name}AggregateResult = Record<string, any>;`,
    "",
    `export interface ${name}GroupByArgs {`,
    "  by: string[];",
    `  where?: ${name}WhereInput;`,
    "  orderBy?: Record<string, SortOrder> | Record<string, SortOrder>[];",
    "  _count?: boolean | Record<string, boolean>;",
    "  _avg?: Record<string, boolean>;",
    "  _sum?: Record<string, boolean>;",
    "  _min?: Record<string, boolean>;",
    "  _max?: Record<string, boolean>;",
    "}",
    "",
    `export type ${name}GroupByResult = Record<string, any>;`,
  ];
}

// ============================================================================
// Client class generation
// ============================================================================

function generateClientClass(schema: Schema): string[] {
  const lines: string[] = [];

  // Filter utility types
  lines.push(
    "// ============================================================================",
  );
  lines.push("// Filter types");
  lines.push(
    "// ============================================================================",
  );
  lines.push("");
  lines.push("export type SortOrder = 'asc' | 'desc';");
  lines.push("");
  lines.push("export interface StringFilter {");
  lines.push("  equals?: string | null;");
  lines.push("  not?: string | StringFilter | null;");
  lines.push("  in?: string[];");
  lines.push("  notIn?: string[];");
  lines.push("  lt?: string;");
  lines.push("  lte?: string;");
  lines.push("  gt?: string;");
  lines.push("  gte?: string;");
  lines.push("  contains?: string;");
  lines.push("  startsWith?: string;");
  lines.push("  endsWith?: string;");
  lines.push("  mode?: 'default' | 'insensitive';");
  lines.push("}");
  lines.push("");
  lines.push("export interface NumberFilter {");
  lines.push("  equals?: number | null;");
  lines.push("  not?: number | NumberFilter | null;");
  lines.push("  in?: number[];");
  lines.push("  notIn?: number[];");
  lines.push("  lt?: number;");
  lines.push("  lte?: number;");
  lines.push("  gt?: number;");
  lines.push("  gte?: number;");
  lines.push("}");
  lines.push("");
  lines.push("export interface BoolFilter {");
  lines.push("  equals?: boolean | null;");
  lines.push("  not?: boolean | BoolFilter | null;");
  lines.push("}");
  lines.push("");
  lines.push("export interface DateTimeFilter {");
  lines.push("  equals?: Date | string | null;");
  lines.push("  not?: Date | string | DateTimeFilter | null;");
  lines.push("  in?: (Date | string)[];");
  lines.push("  notIn?: (Date | string)[];");
  lines.push("  lt?: Date | string;");
  lines.push("  lte?: Date | string;");
  lines.push("  gt?: Date | string;");
  lines.push("  gte?: Date | string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface EnumFilter<T> {");
  lines.push("  equals?: T;");
  lines.push("  not?: T | EnumFilter<T>;");
  lines.push("  in?: T[];");
  lines.push("  notIn?: T[];");
  lines.push("}");
  lines.push("");

  // Client class
  lines.push(
    "// ============================================================================",
  );
  lines.push("// Practor Client");
  lines.push(
    "// ============================================================================",
  );
  lines.push("");
  lines.push("export class PractorClient extends BasePractorClient {");
  lines.push("  constructor(options?: PractorClientOptions) {");
  lines.push("    super(options);");
  lines.push("  }");
  lines.push("");

  // Model accessor properties
  for (const model of schema.models) {
    const camelName = model.name.charAt(0).toLowerCase() + model.name.slice(1);
    lines.push(`  declare ${camelName}: ${model.name}Delegate;`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export default PractorClient;");

  return lines;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Generates the client from a schema file path.
 *
 * @param schemaPath Path to the .practor schema file
 * @param outputDir Output directory for generated TypeScript
 */
export async function generateFromSchema(
  schemaPath: string,
  outputDir: string,
): Promise<void> {
  const { execFileSync } = await import("child_process");

  // Use the Go engine to parse the schema
  const enginePath =
    process.env.PRACTOR_ENGINE_PATH ||
    path.resolve(process.cwd(), "node_modules", ".practor", "practor-engine");

  let schemaJSON: string;
  try {
    schemaJSON = execFileSync(enginePath, ["parse", schemaPath], {
      encoding: "utf-8",
      timeout: 10_000,
    });
  } catch (err: any) {
    // Fallback: try the engine from bin directory
    const binPath = path.resolve(process.cwd(), "bin", "practor-engine");
    schemaJSON = execFileSync(binPath, ["parse", schemaPath], {
      encoding: "utf-8",
      timeout: 10_000,
    });
  }

  const schema = JSON.parse(schemaJSON) as Schema;
  generate(schema, outputDir);
}
